### ISSUE TITLE
how to upload file more than 5 GB perfile

### ISSUE THREAD

**Issue by puangpaka20** [coryrwest/B2.NET#29]
hello i try to follow the code upload large file size and it possible to upload file not over more than 1 GB but my point is i want to upload file over than 15 GB per file This is my code

```
List<byte[]> parts = new List<byte[]>();

using (var stream = System.IO.File.Open(Path.Combine(@"D:\research\2019\Pandora\Pandora_Api\Pandora_Api\video\", items.itemsbucketIds,Path.GetFileNameWithoutExtension(items.fileName), filebuffers.FileName), FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
{
	stream.Seek(0, SeekOrigin.Begin);

	// Read and verify the data.
	byte[] buffer = new byte[100 * (1000 * 1000)];
	for (int i = 0; i < stream.Length; i++)
	{
		Console.WriteLine(i +"/"+ stream.Length);

		// Resize the byte[] array with the size of the remainder of the stream
		if (buffer.Length > stream.Length - i )
		{
			Console.WriteLine(stream.Length);
			buffer = new byte[stream.Length - i];
		}

		stream.Read(buffer, 0, buffer.Length);
		i += buffer.Length;

		parts.Add(buffer);
		Thread.Sleep(1000);
	}
	Array.Clear(buffer, 0, buffer.Length);
}
var shas = new List<string>();
foreach (var part in parts)
{
	string hash = Utilities.GetSHA1Hash(part);
	shas.Add(hash);
}

B2File start = null;
B2File finish = null;
try
{
	start = await client.LargeFiles.StartLargeFile(Path.GetFileName(filebuffers.FileName), "", items.itemsbucketIds);
	for (int i = 0; i < parts.Count; i++)
	{
		var uploadUrl = await client.LargeFiles.GetUploadPartUrl(start.FileId);
		var partResult = await client.LargeFiles.UploadPart(parts[i], i + 1, uploadUrl);
		Thread.Sleep(2000);
	}
	finish = await client.LargeFiles.FinishLargeFile(start.FileId, shas.ToArray());
}
catch (Exception e)
{
	return BadRequest(e);
}
return Ok(finish); 
```

**Comment by coryrwest** [comment]
You should really look at the [large file tests](https://github.com/coryrwest/B2.NET/blob/master/tests/LargeFileTests.cs) for an example on how to do this.

I suspect that you are only getting a 1GB upload because your `buffer` is only 1GB and you aren't using it correctly.

There is a reason that the large file tests are written then way that they are and that is because I originally tried to get it to work with a buffer array outside the loop and could not get a reasonable end result. Granted I am not very well experienced in this type of stream chunking, so I may have been doing things wrong. I can't speak to what your issue might be, but I suggest you use the approach laid out in the large file tests.

Not sure why you are `Thread.Sleep`ing but that shouldn't affect the upload.

**Comment by puangpaka20** [comment]
Ok thank you for notice me, so now i,m skip this feature first but i just wonder when i try to use function download file by ID, it will return file as a "Byte[]", my question is after  i got that what should i do (i use HTML + JS) as a font end side   

Thank you

**Comment by coryrwest** [comment]
I can't speak to possible solutions as you have not provided enough information about how your front end is built. This library is strictly a server-side library. There are plenty of tutorials online about how to send a byte array to the browser, it is a solved problem.

**Comment by puangpaka20** [comment]
Ok thank you very much finally i got the solution for download very very thank you advise me
